### PR TITLE
Properly initialize Network's online state

### LINKED ISSUE #51: Network's initial state doesn't reflect connection status
Navigator's state is started as follows: `state: NetworkProps = { online: false }`. Given that the state is only changed inside `handleOnline` and `handleOffline`, the state only goes online after an `online` event.

For the component to work with SSR, I think it would be better to sync the state with `navigator.onLine` inside `componenDidMount` (something like `this.setState({ online: navigator && navigator.onLine || false })`). I will be submitting a PR.

### PR DESCRIPTION
**Pull request by vhfmag**
Fixes #51

### CODE REVIEW

**Comment by vhfmag** [comment]
But since `componentWillMount` is [the only hook](https://reactjs.org/docs/react-component.html#componentwillmount) called on server rendering, the window should always be available, right? I checked for navigator just in case the component is used in an old browser that doesn't expose the variable (I don't really know if there is suck a browser, to be honest)

**Comment by prichodko** [comment]
Unfortunately I didn't have time to submit my PR fixing this issue, but I did it a bit differently - https://github.com/prichodko/react-fns/commit/7ecd612c0185187885303cff899c0426e27d95e6

I also think that setting listeners in `componentDidMount` is safe.

**Comment by nickbreaton** [comment]
Is there anything blocking this PR?

**Comment by nickbreaton** [comment]
🎉  Awesome thanks!

**Pull request merged**
