### PR TITLE
Add VibrationAPI

### LINKED ISSUE #53: TypeScript error in featureDetection.ts
When trying to build the project, I get a TypeScript error in `src/utils/featureDetection.ts`:

```javascript
9   (window as EventTarget).addEventListener('testPassive', null, opts);
                                                            ~~~~

src/utils/featureDetection.ts(9,59): error TS2345: Argument of type 'null' is not assignable to parameter of type 'EventListener | EventListenerObject | undefined'.


10   (window as EventTarget).removeEventListener('testPassive', null, opts);
                                                                ~~~~

src/utils/featureDetection.ts(10,62): error TS2345: Argument of type 'null' is not assignable to parameter of type 'EventListener | EventListenerObject | undefined'.

```

It seems that we are passing `null` as the 2nd argument, where we should have passed `undefined` as per the type definition in `lib.es6.d.ts`:

```javascript
interface EventTarget {
    addEventListener(type: string, listener?: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    dispatchEvent(evt: Event): boolean;
    removeEventListener(type: string, listener?: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}
```

It looks like this got merged in #45 by @vhfmag (please chip in if you can), but seeing as this makes it impossible to run the `build`command, it seems strange that this wasn't caught, so I'm tempted to believe that this is only a problem on my end, however I cannot figure out why?
I've tried both with the bundled TS version `2.5.0` and the currently newest `2.6.1`.

Am I doing something wrong, or do we indeed need to fix this? If so, I'll happily make a PR.

### PR DESCRIPTION
**Pull request by JReinhold**
Adds support for [Vibration API](https://developer.mozilla.org/en-US/docs/Web/API/Vibration_API). Also Fixes #53, and adds `tslint` as a local package.

The implementation and API is still a work in progress. Currently it exposes the following functions:

- `vibrate(pattern)` - vibrate the specific pattern. The pattern can either be a number, or an array of numbers representing alternating periods of time in which the device is vibrating and not vibrating.
- `persistentVibrate(pattern[, interval])` - add a looping vibration pattern. If `interval` is passed, it will determine when the vibration pattern will restart. If not, it will start again immediately when the pattern has concluded.
- `cancelVibrations()` - Cancels the ongoing vibration pattern, as well as any persistent vibrations that is scheduled.

Feedback on API is welcomed.

Supersedes #56 

## Example usage

```javascript
<Vibration render={({ vibrate, persistentVibrate, cancelVibrations }) => 
  <div>
    <button onClick={() => vibrate(200)}>vibrate once!</button>
    <button onClick={() => vibrate([200, 150, 200, 150, 200])}>vibrate trice!</button>
    <button onClick={() => persistentVibrate([200, 200 200], 2000)}>vibrate loop, explicit 2000 interval!</button>
    <button onClick={() => persistentVibrate([200, 200, 200])}>persistent vibration, implicit 600 interval!</button>
    <button onClick={cancelVibrations}>cancel all vibrations</button>
  </div>
} />
```

## Decisions

- Do we need to document somehow that it only works in certain browsers, on certain devices? either explicit, via link to MDN or caniuse, or not at all?
- Do we need to document that Chrome only allows vibrations if triggered by user gesture?

## TODO

- [x] `<Vibration render/>`
- [x] `withVibration(Inner)` HOC
- [x] write tests for `<Vibration render/>`
- [x] write tests for `withVibration(Inner)` HOC
- [x] test with all browsers (Chrome, Firefox, Safari) on iOS and Android
- [x] make sure it works in SSR
- [x] documentation

### CODE REVIEW

**Comment by RusinovAnton** [comment]
I feel like persistent vibrate feature is redundant since users can implement it by themselves. Do we really want to make this library bloat with features instead of just make components that allow us to use existing API in our React components?

**Comment by JReinhold** [comment]
I get your point, and it could be that it is too much.

The reasoning behind it, is that it makes it easier for the user to add persistent vibrations, than if they had to implement it themselves. Also, if we remove it, the `cancelVibrations()` can seem like an inconsistent feature, as it wouldn't cancel any persistent vibrations, only the one-offs.

It's a balance between ease-of-use for the user, and bloat in the library. Personally, I think it should stay, but if @jaredpalmer thinks it is bloat, lets just remove it.

**Comment by JReinhold** [comment]
No longer work in progress, ready for review and possibly merge @jaredpalmer .

**Comment by jaredpalmer** [comment]
Sorry i accidentally hit merge. This still needs some work. The Vibration API is already very declarative as is. It's 100% sync too. 

This component should probably help with persistent vibrations in a different manner and provide `startVibrate` and `stopVibrate` as render props

**Comment by JReinhold** [comment]
@jaredpalmer so you're thinking something like
- **startVibrate()** start infinite vibration
- **stopVibrate()** stop all vibrations
And then don't support the other functions, as they are almost a replica of the already available functions, is that correct?
How about supporting patterns? I would still argue that making ``startVibrate()`` take an optional `pattern` argument would be useful, as the user could then start a specific vibration pattern that would loop until `stopVibrate()` was called.

IMO that is a nice API.

**Pull request merged**
